kind: ConfigMap
apiVersion: v1
metadata:
  name: demo-native-configmap
data:
  config.test: "Valor do ConfigMap"
  config.test2: "Mais um valor do ConfigMap"
  config.test3: "Um terceiro valor do ConfigMap"